name: Testing
on:
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  ctest-debug:
    name: CTest Debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            LION_BUILD_TESTS=ON
            LION_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Debug

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Debug
          verbose: true

  ctest-release:
    name: CTest Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            LION_BUILD_TESTS=ON
            LION_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Release

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Release
          verbose: true

  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Set up venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install pytest cmake
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Build Python wrapper
        run: |
          pip install .

      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
