name: Tests
on:
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  ctest:
    name: Testing CTest ${{ matrix.config.os }} ${{ matrix.build-type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        build-type: ["Debug", "Release"]
        config:
          # - {
          #     os: windows-latest,
          #     deps-script: "git clone https://github.com/microsoft/vcpkg.git; cd vpckg; .\bootstrap-vcpkg.bat; .\vckpg integrate install; .\vcpkg install gsl gsl:x64-windows"
          #   }
          - {
              os: ubuntu-latest,
              deps-script: "sudo apt-get install libgsl-dev"
            }
          - {
              os: macos-latest,
              deps-script: "brew install gsl"
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          ${{ matrix.config.deps-script }}

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          run-build: true
          options: |
            BUILD_SHARED_LIBS=ON
            LION_BUILD_TESTS=ON
            LION_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=${{ matrix.build-type }}

      - name: Run CTest
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: ${{ matrix.build-type }}
          verbose: true

  pytest:
    name: Testing PyTest ${{ matrix.config.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        config:
          # - {
          #     os: windows-latest,
          #     deps-script: "git clone https://github.com/microsoft/vcpkg.git; cd vpckg; .\bootstrap-vcpkg.bat; .\vckpg integrate install; .\vcpkg install gsl gsl:x64-windows"
          #   }
          - {
              os: ubuntu-latest,
              deps-script: "sudo apt-get install libgsl-dev"
            }
          - {
              os: macos-latest,
              deps-script: "brew install gsl"
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          ${{ matrix.config.deps-script }}

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up env
        run: |
          echo `python --version`
          pip install pytest pytest-md cmake

      - name: Build Python wrapper
        run: |
          pip install .

      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          verbose: true
          emoji: false
          job-summary: true




