name: Testing MacOS
on:
  push:
    branches-ignore:
      - "gh-pages"

jobs:
  ctest-debug:
    name: CTest Debug (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install gsl

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            LION_BUILD_TESTS=ON
            LION_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Debug

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Debug
          verbose: true

  ctest-release:
    name: CTest Release (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install gsl

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure and build
        uses: threeal/cmake-action@v2.0.0
        with:
          generator: Ninja
          run-build: true
          options: |
            LION_BUILD_TESTS=ON
            LION_BUILD_EXAMPLES=OFF
            CMAKE_BUILD_TYPE=Release

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        with:
          build-config: Release
          verbose: true

  pytest-311:
    name: PyTest Python 3.11 (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install gsl

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"

      - name: Set up venv
        run: |
          echo `python --version`
          pip install pytest pytest-md cmake

      - name: Build Python wrapper
        run: |
          pip install .

      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          verbose: true
          emoji: false
          job-summary: true

  pytest-312:
    name: PyTest Python 3.12 (MacOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          submodules: true

      - name: Install dependencies
        run: |
          brew install gsl

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"

      - name: Set up venv
        run: |
          echo `python --version`
          pip install pytest pytest-md cmake

      - name: Build Python wrapper
        run: |
          pip install .

      - name: Run pytest
        uses: pavelzw/pytest-action@v2.2.0
        with:
          verbose: true
          emoji: false
          job-summary: true
